### ISSUE TITLE
群辉 威联通NAS启动docker时如何设置？

### ISSUE THREAD

**Issue by cdphantom** [zhb127/docker-open-dingtalk-pierced#3]
群辉 威联通NAS启动docker时如何设置？

**Comment by zhb127** [comment]
> 

这个仓库包含：

- 把 open dingtalk pierced 的二进制可执行程序封装成容器镜像，暴露出两个环境变量 SUBDOMAIN、PORT 供容器运行时配置。
- 只提供 docker-compose 的方式运行，是因为这个工具本身是：要将其他本地服务暴露到 dingtalk 指定的公网域名，在 macos 容器中，监听本地宿主机的服务端口的时候，要特殊配置，为了规避这里面的一些问题点，只提供 docker-compose。

> 要想直接 docker 运行，可以了解在容器中，获取【宿主机 IP】，然后：docker run --name open-dingtalk-pierced -d -e SUBDOMAIN=xxx.zhb127 -e PORT=【宿主机IP:】80 zhb127/open-dingtalk-pierced
。
