### ISSUE TITLE
请求跟进更新 docker

### ISSUE THREAD

**Issue by ImUlee** [zhb127/docker-open-dingtalk-pierced#4]
钉钉官方貌似更新了新版[https://github.com/open-dingtalk/dingtalk-pierced-client](https://github.com/open-dingtalk/dingtalk-pierced-client)
解决了内存溢出问题以及新域名为 `.cn` 了
docker版本作者能不能辛苦更新一下

----

题外话：docker版本能不能实现添加多个环境变量或者映射出一个配置文件能穿透出多个隧道？

**Comment by zhb127** [comment]
> 钉钉官方貌似更新了新版https://github.com/open-dingtalk/dingtalk-pierced-client 解决了内存溢出问题以及新域名为 `.cn` 了 docker版本作者能不能辛苦更新一下
> 
> 题外话：docker版本能不能实现添加多个环境变量或者映射出一个配置文件能穿透出多个隧道？

get，我看一下时间，以及测试，最迟五一处理一下。

**Comment by ImUlee** [comment]
现在才看到，非常感谢。辛苦更新一下了

**Comment by zhb127** [comment]
> 现在才看到，非常感谢。辛苦更新一下了

更新一版，默认还是 com 顶级域名，可以按需配置为 cn 域名。

另外，因为钉钉官方没提供源代码，配置多个隧道比较不好测试（因为按照 ngrok 的部分配置进行修改测试，好像都不行，因此就暂不考虑了）。

**Comment by zailushang2008** [comment]
> 解决了内存溢出问题

解决了内存溢出问题吗？

**Comment by zhb127** [comment]
> 

已经更新成官方版本：https://github.com/open-dingtalk/dingtalk-pierced-client，可以按照：https://github.com/zhb127/docker-open-dingtalk-pierced#%E5%90%AF%E5%8A%A8-cn-%E7%A4%BA%E4%BE%8B 切换成 cn 域名。

至于是否解决内存溢出，可以关注官方的，这个仓库只是将官方的可执行文件封装成 docker 镜像。

PS：官方文档有说明，仅适用于非生产环境。
